org: imran99744
app: aws-node-api-serverless-project
service: aws-node-api-serverless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:626072240565:table/doTask

functions:
  main:
    handler: src/main.handler
    events:
      - httpApi:
          path: /
          method: get
  insertTodo:
    handler: src/insertTodo.handler
    events:
      - httpApi:
          path: /todo
          method: post
  getTodo:
    handler: src/getTodo.handler
    events:
      - httpApi:
          path: /todo
          method: get
  updateTodo:
    handler: src/finishTodo.handler
    events:
      - httpApi:
          path: /updateTodo/{id}
          method: put

resources:
  Resources:
    doTask:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: doTask
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH